services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: invoice-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "!Admin123"
    ports:
      - "1438:1433"
    volumes:
      - invoice_sqlserver_data:/var/opt/mssql

volumes:
  invoice_sqlserver_data:
